var enemy1 = "Gort";
var distance1 = hero.distanceTo(enemy1);
hero.say(distance1);
var enemy2 = "Smasher";
var distance2 = hero.distanceTo(enemy2);
hero.say(distance2);
var friend3 = "Charles";
var enemy4 = "Gorgnub";
var distance3 = hero.distanceTo(enemy4);
hero.say(distance3);